services:
  waha:
    image: devlikeapro/waha:latest
    container_name: waha
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - WHATSAPP_API_ADMIN_USERNAME=${WAHA_ADMIN_USER:-admin}
      - WHATSAPP_API_ADMIN_PASSWORD=${WAHA_ADMIN_PASS:-change-me}
      - WHATSAPP_API_ALLOWED_ORIGINS=*
      - WHATSAPP_API_CLIENTS=default
      - WHATSAPP_API_DEFAULT_CLIENT_NAME=default
      - WHATSAPP_API_DEFAULT_CLIENT_START=true
    volumes:
      - ./waha-data:/var/lib/whatsapp-http-api

  apiservices:
    build:
      context: .            # <- RAIZ
      dockerfile: app/Dockerfile
    image: apiservices:latest
    container_name: apiservices
    restart: unless-stopped
    depends_on:
      - waha
    env_file:
      - .env                # <- .env da raiz
    environment:
      - API_WAHA_BASE_URL=${API_WAHA_BASE_URL:-http://waha:3000}
    ports:
      - "8000:8000"
